#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

alias ping='ping -c 3'
alias gita='git add'
alias gitc='git commit -m'
alias gitpull='git pull --rebase'
alias gits='git status'
alias octave='octave --no-gui'
alias minecraft='java -jar ~/minecraft/Minecraft.jar'
alias lua='lua -i -e "_PROMPT=\"lua>>\""'
alias netstartx='connectWifi; startx'
alias vim='nvim'
alias bcl='bc -l <<<'
alias squish='/opt/squish/squishide'
alias gitka='gitk --all &'
alias rtm='rememberthemilk &'
alias taskl='clear && task list'
alias sclear='clear; motd ${motd_msg}'


# Customize to your needs...
PATH=$PATH:~/scripts/
